# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

evaluate:
  reader:
    batch_size: 1
    class: "{workspace}/census_infer_reader.py"
    test_data_path: "{workspace}/data/train"

train:
  trainer:
    # for cluster training
    strategy: "async"

  epochs: 3
  workspace: "paddlerec.models.multitask.share-bottom"
  device: cpu

  reader:
    batch_size: 2
    class: "{workspace}/census_reader.py"
    train_data_path: "{workspace}/data/train"

  model:
    models: "{workspace}/model.py"
    hyper_parameters:
      feature_size: 499
      bottom_size: 117
      tower_nums: 2
      tower_size: 8
      learning_rate: 0.001
      optimizer: adam

  save:
    increment:
      dirname: "increment"
      epoch_interval: 2
      save_last: True
    inference:
      dirname: "inference"
      epoch_interval: 4
      save_last: True
