# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace: "paddlerec.models.recall.ssr"

dataset:
- name: dataset_train
  batch_size: 5
  type: QueueDataset
  data_path: "{workspace}/data/train"
  data_converter: "{workspace}/ssr_reader.py"
- name: dataset_infer
  batch_size: 5
  type: QueueDataset
  data_path: "{workspace}/data/test"
  data_converter: "{workspace}/ssr_infer_reader.py"

hyper_parameters:
  vocab_size: 1000
  emb_dim: 128
  hidden_size: 100
  optimizer: 
    class: adagrad
    learning_rate: 0.01
    strategy: async

#use infer_runner mode and modify 'phase' below if infer
mode: train_runner
#mode: infer_runner

runner:
- name: train_runner
  class: train
  device: cpu
  epochs: 3
  save_checkpoint_interval: 2
  save_inference_interval: 4
  save_checkpoint_path: "increment"
  save_inference_path: "inference"
  print_interval: 10
- name: infer_runner
  class: infer
  init_model_path: "increment/0"
  device: cpu

phase:
- name: train
  model: "{workspace}/model.py"
  dataset_name: dataset_train
  thread_num: 1
# - name: infer
#   model: "{workspace}/model.py"
#   dataset_name: dataset_infer
#   thread_num: 1
