# Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# global settings 
debug: false
workspace: "models/rank/wide_deep"


dataset:
  - name: sample_1
    type: DataLoader # or QueueDataset
    batch_size: 5
    data_path: "{workspace}/data/sample_data/train"
    sparse_slots: "label"
    dense_slots: "wide_input:8 deep_input:58"
  - name: infer_sample
    type: DataLoader # or QueueDataset
    batch_size: 5
    data_path: "{workspace}/data/sample_data/train"
    sparse_slots: "label"
    dense_slots: "wide_input:8 deep_input:58"

hyper_parameters:
    optimizer:
        class: adam
        learning_rate: 0.001
    hidden1_units: 75
    hidden2_units: 50
    hidden3_units: 25


mode: [train_runner , infer_runner]
# if infer, change mode to "infer_runner" and change phase to "infer_phase"

runner:
  - name: train_runner
    class: train
    epochs: 1
    device: cpu
    init_model_path: ""
    save_checkpoint_interval: 1
    save_inference_interval: 1
    save_checkpoint_path: "increment"
    save_inference_path: "inference"
    phases: phase1
  - name: infer_runner
    class: infer
    device: cpu
    init_model_path: "increment/0"
    phases: infer_phase

phase:
- name: phase1
  model: "{workspace}/model.py"
  dataset_name: sample_1
  thread_num: 1
- name: infer_phase
  model: "{workspace}/model.py"
  dataset_name: infer_sample
  thread_num: 1
